#!/bin/bash
killall -q polybar

IFS='
'
for m in $(polybar -m); do
  if [[ $m == *"primary"* ]]; then
    bar="main"
  else
    bar="side"
  fi
  [[ $m =~ ^(.+?): ]]
  mon=${BASH_REMATCH[1]}
  MONITOR=$mon polybar $bar 2>&1 | tee -a /tmp/polybar.log & disown
done

